### PR TITLE
Create a requirements.txt file

### PR DESCRIPTION
**Pull request by caattoo**
You need to have a requirements.txt file otherwise your users will not be able to know how to run the program.

### CODE REVIEW

**Comment by CedricVerlinden** [comment]
why

**Comment by caattoo** [comment]
because end user will not understand what to do with this program, they need easy way to know what requirements ,are needed!!

**Comment by caattoo** [comment]
i was very confsued on what to do with README.md sir

**Comment by CedricVerlinden** [comment]
no

**Pull request closed without merging**
